// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwiv9oi-Q6otKbhiD4q5SYqsmpO8QY9KY',
    appId: '1:335942018152:web:433d5946725c4e9d09c7dd',
    messagingSenderId: '335942018152',
    projectId: 'fatima-cure-app-1f4d1',
    authDomain: 'fatima-cure-app-1f4d1.firebaseapp.com',
    storageBucket: 'fatima-cure-app-1f4d1.firebasestorage.app',
    measurementId: 'G-DFWZ1RL3W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzLnFFTt_EoHpF_rU4RlcdRd8cCYc-J4',
    appId: '1:335942018152:android:91fa8af927c5e2ce09c7dd',
    messagingSenderId: '335942018152',
    projectId: 'fatima-cure-app-1f4d1',
    storageBucket: 'fatima-cure-app-1f4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFaXdZlwaYDvzCGh2au46k_69zxjwACY',
    appId: '1:335942018152:ios:bf484026bb6bae3309c7dd',
    messagingSenderId: '335942018152',
    projectId: 'fatima-cure-app-1f4d1',
    storageBucket: 'fatima-cure-app-1f4d1.firebasestorage.app',
    iosBundleId: 'com.example.cure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArFaXdZlwaYDvzCGh2au46k_69zxjwACY',
    appId: '1:335942018152:ios:bf484026bb6bae3309c7dd',
    messagingSenderId: '335942018152',
    projectId: 'fatima-cure-app-1f4d1',
    storageBucket: 'fatima-cure-app-1f4d1.firebasestorage.app',
    iosBundleId: 'com.example.cure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwiv9oi-Q6otKbhiD4q5SYqsmpO8QY9KY',
    appId: '1:335942018152:web:d707e1de4a72110709c7dd',
    messagingSenderId: '335942018152',
    projectId: 'fatima-cure-app-1f4d1',
    authDomain: 'fatima-cure-app-1f4d1.firebaseapp.com',
    storageBucket: 'fatima-cure-app-1f4d1.firebasestorage.app',
    measurementId: 'G-Z013LLTED9',
  );
}
